# Generated by Django 4.2.6 on 2023-10-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_delete_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_favourite',
            new_name='is_deleted',
        ),
    ]
