# Generated by Django 4.2.6 on 2023-10-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_deleted',
        ),
    ]
